aggregations = [
    {
        "name": "eu",
        "iso_codes": [
            "AT",
            "BE",
            "BG",
            "CY",
            "CZ",
            "DE",
            "DK",
            "EE",
            "ES",
            "FI",
            "FR",
            "GR",
            "HR",
            "HU",
            "IE",
            "IT",
            "LT",
            "LU",
            "LV",
            "MT",
            "NL",
            "PL",
            "PT",
            "RO",
            "SE",
            "SI",
            "SK",
        ],
    },
    {
        "name": "eurozone",
        "iso_codes": [
            "AT",
            "BE",
            "CY",
            "DE",
            "EE",
            "ES",
            "FI",
            "FR",
            "GR",
            "HR",
            "IE",
            "IT",
            "LT",
            "LU",
            "LV",
            "MT",
            "NL",
            "PT",
            "SI",
            "SK",
        ],
    },
    {"name": "uk ireland", "iso_codes": ["GB", "IE"]},
    {
        "name": "Asia",
        "iso_codes": [
            "ID",
            "MY",
            "CY",
            "IN",
            "CN",
            "LB",
            "SY",
            "KR",
            "KP",
            "BT",
            "OM",
            "UZ",
            "KZ",
            "TJ",
            "MN",
            "VN",
            "KH",
            "AE",
            "GE",
            "AZ",
            "TR",
            "LA",
            "KG",
            "AM",
            "IQ",
            "IR",
            "QA",
            "SA",
            "PK",
            "TH",
            "KW",
            "TL",
            "BN",
            "MM",
            "BD",
            "AF",
            "TM",
            "JO",
            "NP",
            "YE",
            "HK",
            "PH",
            "LK",
            "TW",
            "JP",
            "SG",
            "BH",
            "MO",
        ],
    },
    {
        "name": "South America",
        "iso_codes": [
            "CL",
            "BO",
            "PE",
            "AR",
            "SR",
            "GY",
            "BR",
            "UY",
            "EC",
            "CO",
            "PY",
            "VE",
        ],
    },
    {
        "name": "Africa",
        "iso_codes": [
            "ET",
            "SS",
            "SO",
            "KE",
            "MW",
            "TZ",
            "MA",
            "CG",
            "CD",
            "NA",
            "ZA",
            "LY",
            "TN",
            "ZM",
            "SL",
            "GN",
            "LR",
            "CF",
            "SD",
            "DJ",
            "ER",
            "CI",
            "ML",
            "SN",
            "NG",
            "BJ",
            "AO",
            "BW",
            "ZW",
            "TD",
            "DZ",
            "MZ",
            "SZ",
            "BI",
            "RW",
            "UG",
            "LS",
            "CM",
            "GA",
            "NE",
            "BF",
            "TG",
            "GH",
            "GW",
            "EG",
            "MR",
            "GQ",
            "GM",
            "MG",
            "KM",
            "ST",
            "CV",
        ],
    },
    {
        "name": "Europe",
        "iso_codes": [
            "FR",
            "UA",
            "BY",
            "LT",
            "RU",
            "CZ",
            "DE",
            "EE",
            "LV",
            "NO",
            "SE",
            "FI",
            "LU",
            "BE",
            "MK",
            "AL",
            "ES",
            "DK",
            "RO",
            "HU",
            "SK",
            "PL",
            "IE",
            "GB",
            "GR",
            "AT",
            "IT",
            "CH",
            "NL",
            "LI",
            "RS",
            "HR",
            "SI",
            "BG",
            "SM",
            "MC",
            "AD",
            "ME",
            "BA",
            "PT",
            "MD",
            "VA",
            "IS",
            "MT",
            "JE",
            "GG",
            "IM",
            "AX",
        ],
    },
    {
        "name": "North America",
        "iso_codes": [
            "CR",
            "NI",
            "SX",
            "HT",
            "DO",
            "SV",
            "GT",
            "CU",
            "HN",
            "US",
            "CA",
            "MX",
            "BZ",
            "PA",
            "GL",
            "CW",
            "AW",
            "BS",
            "TT",
            "GD",
            "VC",
            "BB",
            "LC",
            "DM",
            "AG",
            "KN",
            "JM",
        ],
    },
    {
        "name": "Oceania",
        "iso_codes": [
            "PG",
            "AU",
            "FJ",
            "NZ",
            "KI",
            "MH",
            "TO",
            "WS",
            "SB",
            "TV",
            "NR",
            "FM",
            "VU",
            "PW",
        ],
    },
    {
        "name": "americas",
        "iso_codes": [
            "CL",
            "BO",
            "PE",
            "AR",
            "SR",
            "GY",
            "BR",
            "UY",
            "EC",
            "CO",
            "PY",
            "VE",
            "CR",
            "NI",
            "SX",
            "HT",
            "DO",
            "SV",
            "GT",
            "CU",
            "HN",
            "US",
            "CA",
            "MX",
            "BZ",
            "PA",
            "GL",
            "CW",
            "AW",
            "BS",
            "TT",
            "GD",
            "VC",
            "BB",
            "LC",
            "DM",
            "AG",
            "KN",
            "JM",
        ],
    },
    {
        "name": "South-Eastern Asia",
        "iso_codes": ["ID", "MY", "VN", "KH", "LA", "TH", "TL", "BN", "MM", "PH", "SG"],
    },
    {
        "name": "South America",
        "iso_codes": [
            "CL",
            "BO",
            "PE",
            "AR",
            "SR",
            "GY",
            "BR",
            "UY",
            "EC",
            "CO",
            "PY",
            "VE",
        ],
    },
    {
        "name": "Western Asia",
        "iso_codes": [
            "CY",
            "LB",
            "SY",
            "OM",
            "AE",
            "GE",
            "AZ",
            "TR",
            "AM",
            "IQ",
            "QA",
            "SA",
            "KW",
            "JO",
            "YE",
            "BH",
        ],
    },
    {
        "name": "Southern Asia",
        "iso_codes": ["IN", "BT", "IR", "PK", "BD", "AF", "NP", "LK", "MV"],
    },
    {
        "name": "Eastern Asia",
        "iso_codes": ["CN", "KR", "KP", "MN", "HK", "TW", "JP", "MO"],
    },
    {
        "name": "Eastern Africa",
        "iso_codes": [
            "ET",
            "SS",
            "SO",
            "KE",
            "MW",
            "TZ",
            "ZM",
            "DJ",
            "ER",
            "ZW",
            "MZ",
            "BI",
            "RW",
            "UG",
            "MG",
            "SC",
            "MU",
            "KM",
        ],
    },
    {
        "name": "Western Europe",
        "iso_codes": ["FR", "DE", "LU", "BE", "AT", "CH", "NL", "LI", "MC"],
    },
    {"name": "Northern Africa", "iso_codes": ["MA", "LY", "TN", "SD", "DZ", "EG"]},
    {
        "name": "Central America",
        "iso_codes": ["CR", "NI", "SV", "GT", "HN", "MX", "BZ", "PA"],
    },
    {
        "name": "Middle Africa",
        "iso_codes": ["CG", "CD", "CF", "AO", "TD", "CM", "GA", "GQ", "ST"],
    },
    {
        "name": "Eastern Europe",
        "iso_codes": ["UA", "BY", "RU", "CZ", "RO", "HU", "SK", "PL", "BG", "MD"],
    },
    {"name": "Southern Africa", "iso_codes": ["NA", "ZA", "BW", "SZ", "LS"]},
    {
        "name": "Caribbean",
        "iso_codes": [
            "SX",
            "HT",
            "DO",
            "CU",
            "CW",
            "AW",
            "BS",
            "TT",
            "GD",
            "VC",
            "BB",
            "LC",
            "DM",
            "AG",
            "KN",
            "JM",
        ],
    },
    {"name": "Central Asia", "iso_codes": ["UZ", "KZ", "TJ", "KG", "TM"]},
    {
        "name": "Northern Europe",
        "iso_codes": [
            "LT",
            "EE",
            "LV",
            "NO",
            "SE",
            "FI",
            "DK",
            "IE",
            "GB",
            "IS",
            "JE",
            "GG",
            "IM",
            "AX",
        ],
    },
    {
        "name": "Southern Europe",
        "iso_codes": [
            "MK",
            "AL",
            "ES",
            "GR",
            "IT",
            "RS",
            "HR",
            "SI",
            "SM",
            "AD",
            "ME",
            "BA",
            "PT",
            "VA",
            "MT",
        ],
    },
    {
        "name": "Western Africa",
        "iso_codes": [
            "SL",
            "GN",
            "LR",
            "CI",
            "ML",
            "SN",
            "NG",
            "BJ",
            "NE",
            "BF",
            "TG",
            "GH",
            "GW",
            "MR",
            "GM",
            "CV",
        ],
    },
    {"name": "Northern America", "iso_codes": ["US", "CA", "GL"]},
    {"name": "Melanesia", "iso_codes": ["PG", "FJ", "SB", "VU"]},
    {"name": "Australia and New Zealand", "iso_codes": ["AU", "NZ"]},
    {"name": "Micronesia", "iso_codes": ["KI", "MH", "NR", "FM", "PW"]},
    {"name": "Polynesia", "iso_codes": ["TO", "WS", "TV"]},
    {"name": "World", "iso_codes": [""]},
]
